declare module '@editorjs/header'
declare module '@editorjs/list'
declare module '@editorjs/quote'
declare module '@editorjs/code'
declare module '@editorjs/marker'
declare module '@editorjs/inline-code'
declare module 'editorjs-html'
