export const API_ENDPOINT = {
  // authentication
  LOGIN: '/api/auth/login',
  LOGOUT: '/api/auth/logout',
  REGISTER: 'api/auth/register',
  REFRESH_TOKEN: 'api/auth/refresh-token',
  // project group task
  CREATE_PROJECT: '/api/task-group/create',
  GET_PROJECTS: '/api/task-group/get-list',
  UPDATE_PROJECT: '/api/task-group/update',
  DELETE_PROJECT: '/api/task-group/update-status',
  GET_PROJECT_DETAIL: '/api/task-group/get-detail',
  SEARCH_PROJECT: '/api/task-group/name-search',
  // task
  CREATE_TASK: '/api/task/create',
  GET_TASKS: '/api/task/get-list',
  UPDATE_TASK: '/api/task/update',
  DELETE_TASK: '/api/task/remove',
  ASIGN_TASK: '/api/task/assign-task',
  UPDATE_PRIORITY: '/api/task/update-priority',
  UPDATE_STATUS: '/api/task/update-status',
  UPDATE_CHECKLIST: '/api/task/update-checklist',
  // USER
  GET_MEMBER_TASK: '/api/user/get-task-group-member-list',
  GET_ALL_USER: '/api/user/get-all',
  INVITE_USER: '/api/task-group/add-members',
  CREATE_MEMBER: '/api/user/create-worker-account',
  // Task
  GET_TASK_DETAIL: '/api/task/get-detail',
  // Comment
  CREATE_COMMENT: '/api/comment/create',
  GET_LIST_COMMENT: '/api/comment/get-list',
  UPDATE_COMMENT: '/api/comment/update',
  REMOVE_COMMENT: '/api/comment/remove',
  UPDATE_COMMENT_STATUS: '/api/comment/update-status',
  // leaves
  GET_LIST_LEAVES: '/api/absence-request/get-list',
  GET_LIST_LEAVES_MANAGER: '/api/absence-request/get-subordinates-list',
  UPDATE_LEAVES: '/api/absence-request/update',
  UPDATE_LEAVES_STATUS: '/api/absence-request/update-status',
  CREATE_LEAVES: '/api/absence-request/create',
  GET_USER_APPROVE_LEAVES: '/api/absence-request/get_approvable_users',
  REMOVE_LEAVES: '/api/absence-request/remove',
  // profile
  GET_PROFILE: '/api/user/get-info',
  UPDATE_EMAIL: '/api/user/update-email',
  UPDATE_AVATAR: '/api/user/update-avatar',
  UPDATE_NAME: '/api/user/update-name',
  UPDATE_PHONE: '/api/user/update-phone-number',
  // dashboard
  DASHBOARD_LEAVES: '/api/dashboard/team-stats',
  DASHBOARD_OVERVIEW: '/api/dashboard/stats',
  DASHBOARD_ASSIGNMENTS: '/api/dashboard/stats',
  DASHBOARD_PROJECT_PROGRESS_DAY: '/api/dashboard/project-progress',
  DASHBOARD_OVERDUE_TASK: '/api/dashboard/overdue-tasks',
  DASHBOARD_PROJECT_RATIO: '/api/dashboard/project-status-ratio',
  // web push notification
  NOTIFICATION_SUBSCRIBE: '/api/notifications/webpush/subscribe',
  NOTIFICATION_TEST_PUSH: '/api/notifications/webpush/test',
  // upload file
  UPLOAD_FILE: '/api/upload/file',
  // documents
  UPLOAD_DOCUMENT: '/api/upload/document',
  GET_DOCUMENTS: '/api/upload/document/get-list',
}
